name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install docs requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Install
        run: |
          pushd geoarrow-pyarrow
          pip install ".[test]"
          popd

          pushd geoarrow-pandas
          pip install ".[test]"
          popd

      - name: Build docs
        run: |
          pushd docs
          pandoc ../README.md --from markdown --to rst -s -o source/README_generated.rst
          sphinx-build source _build/html

      - name: Upload built documentation
        uses: actions/upload-artifact@main
        with:
          name: docs
          path: docs/_build/html

      - name: Clone gh-pages branch
        if: success() && github.repository == 'geoarrow/geoarrow-python' && github.ref == 'refs/heads/main'
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages-clone

      - name: Update development documentation
        if: success() && github.repository == 'geoarrow/geoarrow-python' && github.ref == 'refs/heads/main'
        env:
          DOC_TAG: "main"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd pages-clone
          if [ -d "$DOC_TAG" ]; then
            git rm -rf "$DOC_TAG"
          fi
          mkdir "$DOC_TAG"
          cp -R ../docs/_build/html/* "$DOC_TAG"
          git add *
          git commit --allow-empty -m"update documentation for tag $DOC_TAG"
          git push
          cd ..
